repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest  -m "not integration"
        types: [python]
        pass_filenames: false

      - id: pytest-cov
        name: pytest-cov
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=100  -m "not integration"
        types: [python]
        pass_filenames: false

      - id: pytest-full
        name: pytest-full
        stages: [push]
        language: system
        entry: pipenv run pytest
        types: [python]
        pass_filenames: false

